= Edge branches WiFi automation with AAP and SD-WAN Meraki Cheat Sheet
:experimental: true
:product-name:

This cheat sheet covers the commands used for working with https://meraki.cisco.com[Cisco Meraki], one of the Cisco enterprise cloud managed networking solutions, a popular solution for managing access points, security appliances, L2 and L3 switches, and more. This cheatsheet will show how to use Automated NetOps through a GitHub integration with Ansible Automation Platform to manage the Meraki controlled devices configuration as code.

The steps configured here can be recreated using Cisco Devnet Sandbox Lab https://devnetsandbox.cisco.com/RM/Diagram/Index/aa48e6e2-3e59-4b87-bfe5-7833c45f8db8?diagramType=Topology[Meraki Small Business], which allows an 8 hr reservation by default, and after the reservation is ready it will allow you to get admin access to configure Wireless and networking for your specific settings.

The overall use case will follow this flow: 
----
1. Cisco DevNet sandbox reservation if you do not have your own Meraki environment to configure (optional)
2. Cisco Meraki dashboard API Key generation to allow the provisioning from Ansible Automation Platform
3. Configure GitHub Repo with the wireless settings
4. Generate the PAT credentials from GitHub and establish the integration with Ansible Automation Platform
5. Configure the Ansible Automation Platform project, template using the GitHub repo webhook
6. Edit the wireless settings to observe an automatic trigger of the automation job
----

The Configuration flow will go like this:

GitHub Repo (through webhook) -> Ansible Automation Platform -> Meraki Dashboard Controller API -> Networking device (Access Point)

== Note

The `$` symbol that proceeds commands in the examples represents the command line prompt.

== Cisco DevNet sandbox reservation (optional)
For this cheatsheet we will use https://devnetsandbox.cisco.com/RM/Diagram/Index/aa48e6e2-3e59-4b87-bfe5-7833c45f8db8?diagramType=Topology[Meraki Small Business] as it will allow some specific provisioning tasks.

Once you login with your Cisco DevNet credentials, I am using my personal Google account for this setup, you click on `Reserve` button and after you reconfirm the reservation, a Setup job will be triggered. 
Wait around 5 minutes to get a confirmation mail with the credentials you will use to login into the https://n149.meraki.com[Cisco Meraki dashboard], you might get the username and will be asked to reset your password.
Once you login with your Cisco DevNet credentials, I am using my personal Google account for this setup, you click on `Reserve` button and after you reconfirm the reservation, a Setup job will be triggered. Wait around 5 minutes to get a confirmation mail with the credentials that your will use to login into the https://n149.meraki.com[Cisco Meraki dashboard], you might get the username and will be asked to reset your password.

When you connect into https://n149.meraki.com[Cisco Meraki dashboard] a anonymized network will be created with your mail, in my case the network name is: `DNSMB2-dxxxxxxxlgmail.com `

=== Note

The network generated automatically with your mail account as an input is the network that will give you writing access. Use that specific network for all this demo, and do not use a different one.


== Cisco Meraki dashboard steps

=== Organization - Summary

Shows all `Organization` settings, select `Networks` to view all Networks available for your `Organization`. 

*Example:*

The following image shows the Organization settings available: <<<<<<----

=== Organization - Networks

Shows all Organization `Networks`, click on your assigned `Network` to view the settings.

*Example:*

The following image shows the Networks available: <<<<<<----

=== Organization - Configure

Allows you to edit configurations for the `Organization`, which by default will be named "DevNet Sandbox". Almost at the end of this page, you can find `Dashboard API access`. 

*Example:*

The following image shows the Organization settings available: <<<<<<----

=== Organization - Configure - Dashboard API access

Will show you two options: `Enable access to the Cisco Meraki Dashboard API` and if you click on the hyperlink `Profile` you can generate an API key to allows the configuration from Ansible Automation Platform.

=== User profile - API access

You can reach this configuration settings with two options: 

1. Clicking the hyperlink `Profile` from `Organization - Configure - Dashboard API access` and going to `API access`.
2. Selecting from the top right corner the User icon and clicking on it to select `My profile`and later `API access`.

Once there click on `Generate new API key`. 

=== Note
Make sure you save the API key as it will be available for copy only once. When you finish click on `Done`button. 

=== User profile - API access - API keys

Once you generate at least one API key, you can generate additional ones, or `Revoke`specific API keys. As a general practice make sure to revoke API keys if you are not using them.

=== Wireless - Configure - SSIDs

You can see that as part of the Sandbox enablement you will have SSID 1 configured, in my environment I have one SSID named: "DNSMB2 - wireless WiFi", you can manually disable the network, rename it, and also edit Access control configuration.
After every change make sure to click on `Save Changes` button or `cancel`. 

== Configure GitHub Repo with the wireless settings



